### PR TITLE
README.md: add dependencies section

### PR DESCRIPTION
**Pull request by Hyask**

### CODE REVIEW

**Comment by jvoisin** [comment]
The dependency is needed only for the per ltool, care to specify this?

**Comment by Hyask** [comment]
I put that as a subpart of the command-line tool part, isn't that enough?

**Comment by atenart** [comment]
Can you updated the command line tool section instead? It already contains information on how to download and use it, it seems like the place to add a dependency note.

Thanks!

**Comment by Hyask** [comment]
It's already in that section. Please read the whole file here: 

https://github.com/Hyask/pasthis/blob/02be0a96a4d560a5c9fd3ebbffb68c6e401e2bd5/README.md#command-line-tool

**Comment by atenart** [comment]
Oh. I see. Could you s/dependencies/dependency/, s/plugin/Perl module/ and remove the 'may' word then? Thanks!

**Comment by Hyask** [comment]
Done

**Comment by atenart** [comment]
Merged, thanks!

**Pull request merged**
